<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demonstration.proto

namespace GPBMetadata;

class Demonstration
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5010a1364656d6f6e7374726174696f6e2e70726f746f120a6f6e656f" .
            "666572726f722289010a0d44656d6f6e7374726174696f6e120e0a046e61" .
            "6d651804200128094800123b0a0b7375625f6d6573736167651809200128" .
            "0b32242e6f6e656f666572726f722e44656d6f6e7374726174696f6e2e53" .
            "75624d65737361676548001a1a0a0a5375624d657373616765120c0a046e" .
            "616d65180420012809420f0a0d746573745f617267756d656e7462067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

