<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demonstration.proto

namespace Oneoferror;

if (false) {
    /**
     * This class is deprecated. Use Oneoferror\Demonstration\SubMessage instead.
     * @deprecated
     */
    class Demonstration_SubMessage {}
}
class_exists(Demonstration\SubMessage::class);
@trigger_error('Oneoferror\Demonstration_SubMessage is deprecated and will be removed in the next major release. Use Oneoferror\Demonstration\SubMessage instead', E_USER_DEPRECATED);

