<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demonstration.proto

namespace Oneoferror\Demonstration;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>oneoferror.Demonstration.SubMessage</code>
 */
class SubMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 4;</code>
     */
    private $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Demonstration::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SubMessage::class, \Oneoferror\Demonstration_SubMessage::class);

